<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TestTfm)</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzer.Testing" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" />
    <PackageReference Include="Verify.SourceGenerators" />
    <PackageReference Include="Verify" />
    <PackageReference Include="xunit.v3.assert" />
    <PackageReference Include="NXTest" />
    <ProjectReference Include="../../src/serde/Serde.csproj" />
    <ProjectReference Include="../../src/generator/SerdeGenerator.csproj" />
  </ItemGroup>
</Project>
