//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/andy/code/serde-dn/src/serde-xml/ReflectionTypeName.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IReflectionTypeNameListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ReflectionTypeNameBaseListener : IReflectionTypeNameListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ReflectionTypeNameParser.topTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopTypeName([NotNull] ReflectionTypeNameParser.TopTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ReflectionTypeNameParser.topTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopTypeName([NotNull] ReflectionTypeNameParser.TopTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ReflectionTypeNameParser.fullType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFullType([NotNull] ReflectionTypeNameParser.FullTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ReflectionTypeNameParser.fullType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFullType([NotNull] ReflectionTypeNameParser.FullTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ReflectionTypeNameParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] ReflectionTypeNameParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ReflectionTypeNameParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] ReflectionTypeNameParser.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ReflectionTypeNameParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedName([NotNull] ReflectionTypeNameParser.QualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ReflectionTypeNameParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedName([NotNull] ReflectionTypeNameParser.QualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ReflectionTypeNameParser.generics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenerics([NotNull] ReflectionTypeNameParser.GenericsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ReflectionTypeNameParser.generics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenerics([NotNull] ReflectionTypeNameParser.GenericsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
