using System;

namespace Serde;

/// <summary>
/// Represents a "serialize" object. A serialize object contains the logic about how to serialize a
/// particular type with an arbitrary serializer. It is usually a singleton object -- almost all
/// types should not need to modify how they are serialized based on some mutable state. The
/// serialize object for a type is usually acquired through an <see cref="ISerializeProvider{T}" />.
///
/// The implementation of this interface is usually generated by the <c>Serde</c> code generator.
/// Most implementations are straightforward based on the layout of the type. For example, a
/// Point(int X, int Y) would be serialized by writing the X and Y values into the serializer:
///
/// <code>
/// public void Serialize(Point value, ISerializer serializer)
/// {
///     var info = SerdeInfoProvider.GetInfo(this);
///     var typeSer = serializer.WriteType(info);
///     typeSer.WriteI32(info, 0, value.X);
///     typeSer.WriteI32(info, 1, value.Y);
///     typeSer.End(info);
/// }
/// </code>
/// </summary>
public interface ISerialize<T> : ISerdeInfoProvider
{
    void Serialize(T value, ISerializer serializer);

    /// <summary>
    /// Serialize a value as a field (or element) of a type.
    /// </summary>
    void SerializeAsField(ITypeSerializer typeSerializer, ISerdeInfo serdeInfo, int index, T value)
    {
        var s = typeSerializer.WriteFieldStart(serdeInfo, index);
        Serialize(value, s);
        typeSerializer.WriteFieldEnd(serdeInfo, index, s);
    }
}

[Obsolete("Use ISerialize<T>.SerializeAsField instead")]
public interface ITypeSerialize<T> : ISerialize<T>
{
    void Serialize(T value, ITypeSerializer serializer, ISerdeInfo info, int index) =>
        SerializeAsField(serializer, info, index, value);
}

public static class TypeSerialize
{
    [Obsolete("Use ISerialize<T>.SerializeAsField instead")]
    public static ITypeSerialize<T> GetOrBox<T, TProvider>()
        where TProvider : ISerializeProvider<T>
    {
        var ser = TProvider.Instance;
        return ser switch
        {
            ITypeSerialize<T> typeSer => typeSer,
            _ => new TypeSerializeAdapter<T>(ser),
        };
    }

#pragma warning disable CS0618 // ITypeSerialize is obsolete
    private sealed class TypeSerializeAdapter<T>(ISerialize<T> underlying) : ITypeSerialize<T>
    {
        public ISerdeInfo SerdeInfo => underlying.SerdeInfo;

        public void Serialize(T value, ISerializer serializer) =>
            underlying.Serialize(value, serializer);

        public void SerializeAsField(
            ITypeSerializer typeSerializer,
            ISerdeInfo serdeInfo,
            int index,
            T value
        ) => underlying.SerializeAsField(typeSerializer, serdeInfo, index, value);
    }
#pragma warning restore CS0618
}

public interface ISerializeProvider<T>
{
    static abstract ISerialize<T> Instance { get; }
}

public static class SerializeProvider
{
    public static ISerialize<T> GetSerialize<T>()
        where T : ISerializeProvider<T> => T.Instance;

    public static ISerialize<T> GetSerialize<T, TProvider>()
        where TProvider : ISerializeProvider<T> => TProvider.Instance;
}
