using System;

namespace Serde;

/// <summary>
/// Represents a "serialize" object. A serialize object contains the logic about how to serialize a
/// particular type with an arbitrary serializer. It is usually a singleton object -- almost all
/// types should not need to modify how they are serialized based on some mutable state. The
/// serialize object for a type is usually acquired through an <see cref="ISerializeProvider{T}" />.
///
/// The implementation of this interface is usually generated by the <c>Serde</c> code generator.
/// Most implementations are straightforward based on the layout of the type. For example, a
/// Point(int X, int Y) would be serialized by writing the X and Y values into the serializer:
///
/// <code>
/// public void Serialize(Point value, ISerializer serializer)
/// {
///     var info = SerdeInfoProvider.GetInfo(this);
///     var typeSer = serializer.WriteType(info);
///     typeSer.WriteI32(info, 0, value.X);
///     typeSer.WriteI32(info, 1, value.Y);
///     typeSer.End(info);
/// }
/// </code>
/// </summary>
public interface ISerialize<T> : ISerdeInfoProvider
{
    void Serialize(T value, ISerializer serializer);
}

/// <summary>
/// This is a perf optimization. It allows primitive types (and only primitive types) to be
/// serialized without boxing. It is only useful for serializing collections.
/// </summary>
public interface ITypeSerialize<T>
{
    void Serialize(T value, ITypeSerializer serializer, ISerdeInfo info, int index);
}

public static class TypeSerialize
{
    /// <summary>
    /// Checks if the <typeparamref name="TProvider"/> produces a type that implements <see
    /// cref="ITypeSerialize{T}" />. If it does, it returns that type. Otherwise, it returns a <see
    /// cref="BoxProxy.Ser{T, TProvider}"/>.
    /// </summary>
    public static ITypeSerialize<T> GetOrBox<T, TProvider>()
        where TProvider : ISerializeProvider<T>
    {
        var ser = TProvider.Instance;
        return ser switch
        {
            ITypeSerialize<T> typeSer => typeSer,
            _ => BoxProxy.Ser<T, TProvider>.Instance
        };
    }
}


public interface ISerializeProvider<T>
{
    abstract static ISerialize<T> Instance { get; }
}

public static class SerializeProvider
{
    public static ISerialize<T> GetSerialize<T>() where T : ISerializeProvider<T> => T.Instance;
    public static ISerialize<T> GetSerialize<T, TProvider>()
        where TProvider : ISerializeProvider<T>
        => TProvider.Instance;
}


